services:
  postgres:
    image: postgres:16
    container_name: tea_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tea
      POSTGRES_PASSWORD: tea123
      POSTGRES_DB: tea_db
    volumes:
      - tea_pg_data:/var/lib/postgresql/data

volumes:
  tea_pg_data:
